/* =========================================================
   VISION AURA STUDIO — Portfolio Page Renderer
   Shared by every /portfolio/*.html page.
   Do NOT edit this file to add projects — edit the matching
   file in js/data/ instead. This file just reads that data.

   Behavior: clicking any project card opens its file
   (video / image / website link) in a NEW BROWSER TAB.
   ========================================================= */
(function(){
  "use strict";

  var grid = document.getElementById("projectsGrid");
  if(!grid) return;

  var items = (typeof PROJECTS !== "undefined") ? PROJECTS : [];

  if(!items.length){
    grid.innerHTML = '<div class="projects-empty">No projects added yet — add your first one in the matching js/data file.</div>';
    return;
  }

  items.forEach(function(p, i){
    var card = document.createElement("article");
    card.className = "project-card";
    card.style.animationDelay = (i * 90) + "ms";
    card.setAttribute("data-video", p.video || "");

    card.innerHTML =
      '<div class="project-thumb" style="background-image:url(\'' + p.thumbnail + '\')"></div>' +
      '<button class="project-play" aria-label="Open project" type="button">' +
        '<svg viewBox="0 0 24 24"><polygon points="6,4 20,12 6,20"/></svg>' +
      '</button>' +
      '<div class="project-info">' +
        '<h3>' + p.title + '</h3>' +
        '<p>' + p.description + '</p>' +
      '</div>';

    grid.appendChild(card);
  });

  // Every card, whatever the category, opens its file in a new tab.
  grid.addEventListener("click", function(e){
    var card = e.target.closest(".project-card");
    if(!card) return;
    var url = card.getAttribute("data-video");
    if(url){ window.open(url, "_blank", "noopener"); }
  });

  /* ---------------- Footer year ---------------- */
  var yearEl = document.getElementById("year");
  if(yearEl){ yearEl.textContent = new Date().getFullYear(); }

  /* ---------------- Navbar scroll state ---------------- */
  var navbar = document.getElementById("navbar");
  window.addEventListener("scroll", function(){
    if(navbar){ navbar.classList.toggle("scrolled", window.scrollY > 20); }
  }, { passive: true });

})();